export const initialForm = {
  institutionType: '',
  institutionName: '',
  institutionNature: '',
  institutionMemberCode: '',
  institutionBranch: '',
  institutionIncoporationNumber: '',
  institutionTIN: '',
  institutionIncoporationDate: '',
  institutionDateJoined: '',
  institutionRegion: '',
  institutionDistrict: '',
  institutionWard: '',
  institutionResidency: '',
  firstName: '',
  middleName: '',
  surname: '',
  memberCode: '',
  branch: '',
  memberEmployed: false,
  sendSms: false,
  registerMobileWallet: false,
  title: '',
  nationality: '',
  tribe: '',
  levelOfEducation: '',
  dateOfBirth: '',
  dateJoined: '',
  gender: '',
  maritalStatus: '',
  idType: '',
  idNumber: '',
  placeIssue: '',
  dateIssued: '',
  expiryDate: '',
  povertyLevel: '',
  region: '',
  district: '',
  ward: '',
  country: '',
  city: '',
  address: '',
  mobilePhoneNumber: '',
  emailAddress: '',
  refereeName: '',
  refereeAddress: '',
  refereeMobilePhone: '',
  refereeEmailAddress: '',
  nextOfKinName: '',
  nextOfKinAddress: '',
  nextOfKinRelationship: '',
  nextOfKinMobilePhone: '',
  employer: '',
  employmentCountry: '',
  employmentCity: '',
  employmentAddress: '',
  employmentMobilePhone: '',
  employmentEmailAddress: '',
  employmentNumber: '',
  designation: '',
  department: '',
  yearsWithCurrentEmployment: '',
  currentSalary: '',
  biometricPhotoName: '',
  biometricSignatureName: '',
  applicationFormName: '',
  registrationFee: '',
  contributionAccountNumber: '',
  contributionAccountName: '',
  sharePrice: '',
  sharesPurchase: '',
  shareValue: '',
  savingMode: '',
  savingAmount: '',
  accountSignatory: '',
  deductedFromSourcePayroll: false,
  residency: '',
  chairName: '',
  chairTIN: '',
  chairMobilePhone: '',
  chairEmailAddress: '',
  chairAccountSignatory: false,
  viceChairName: '',
  viceChairTIN: '',
  viceChairMobilePhone: '',
  viceChairEmailAddress: '',
  viceChairAccountSignatory: false,
  treasurerName: '',
  treasurerTIN: '',
  treasurerMobilePhone: '',
  treasurerEmailAddress: '',
  treasurerAccountSignatory: false,
  secretaryName: '',
  secretaryTIN: '',
  secretaryMobilePhone: '',
  secretaryEmailAddress: '',
  secretaryAccountSignatory: false,
  referenceDetailsName: '',
  referenceDetailsAddress: '',
  referenceDetailsMobilePhone: '',
  referenceDetailsEmailAddress: '',
  signatory1: '',
  signatory3: '',
  defaultBatch: '',
  // Background fields for Institution
  backgroundYearOfFormation: '',
  backgroundMembershipByGenderInitial: '',
  backgroundRegistrationAuthority: '',
  backgroundMembershipByGenderCurrent: '',
  backgroundDropoutsRateByGender: '',
  // Operations fields for Institution
  operationsYearsOfOperation: '',
  operationsProfitMargin: '',
  operationsRecordsMaintenance: '',
  operationsProximityToEndBorrowers: '',
  // Trainings for Institution
  trainings: [
    {
      id: 1,
      yearOfTraining: '',
      typeOfTraining: '',
      duration: '',
      supportedBy: '',
      numberOfBeneficiaries: '',
    },
  ],
  // Projects for Institution
  projects: [
    {
      id: 1,
      year: '',
      projectType: '',
      status: '',
      supportedBy: '',
      remarks: '',
    },
  ],
  // Committee Members for Institution
  committeeMembers: [
    {
      id: 1,
      names: '',
      positions: '',
      literacyExperiences: '',
    },
  ],
  printReceipt: false,
};
